name: Rust STM32F767 Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: rustfmt

      #- name: Install ARM toolchain
      # run: |
      #   sudo apt-get update
      #   sudo apt-get install -y gcc-arm-none-eabi

      #- name: Install cargo generate
      #  run: cargo install cargo-generate

      #    - name: Install cargo embed
      #      run: cargo install cargo-embed

      - name: Install Rust targets
        run: rustup target add thumbv7em-none-eabihf
      - name: Rust build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: target/thumb
